apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachedeployment
  namespace: apachenamespace 
spec:
  replicas: 2  # Initial replica count
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache 
    spec:
      containers:
        - name: apachecontainer 
          image: httpd:latest 
          ports: 
          - containerPort: 80 
