apiVersion: v1
kind: Service
metadata:
  name: apacheservice
  namespace: apachenamespace
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30000 # NodePort for external access
  type: NodePort
