# Deployment for multiple replicas and rolling update
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myfirstdeployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:   
      name: "mypod"         # Corrected indentation and structure
      labels:
        app: webapp
    spec:
      containers:
        - name: "firstcontainer"
          image: amitkumar0441/dockerwebapp:latest
          ports:
            - containerPort: 80



---
apiVersion: v1 
kind: Service 
metadata: 
 name: "myfirstservice" 
spec: 
 selector:
  app: webapp 
 ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # Container port
      nodePort: 30053   # NodePort for external access
 type: NodePort