apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: amit-rolebinding
  namespace: mycustomnamespace
subjects:
- kind: ServiceAccount
  name: amit-sa
  namespace: mycustomnamespace
roleRef:
  kind: Role
  name: amit-role
  apiGroup: rbac.authorization.k8s.io
